# Generated by Django 5.1.4 on 2025-01-06 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basic_items', models.JSONField(null=True)),
                ('summary', models.TextField(null=True)),
                ('doctor_modified_summary', models.TextField(null=True)),
                ('conversation', models.JSONField(null=True)),
                ('sick_leave', models.CharField(max_length=8, null=True)),
                ('referral_letter', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TentativeMap',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Web.patient')),
            ],
        ),
    ]
