# Generated by Django 5.1.4 on 2025-01-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='summary',
            new_name='patient_ch_summary',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_en_summary',
            field=models.TextField(null=True),
        ),
    ]
