# Generated by Django 5.1.4 on 2025-03-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Web', '0002_rename_summary_patient_patient_ch_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='asr_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_record',
            field=models.TextField(null=True),
        ),
    ]
